apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform project
  sourceRepos:
    - 'https://github.com/BernardoJose90/*'   
  destinations:
    - namespace: 'crossplane-system'
      server: 'https://kubernetes.default.svc'
    - namespace: 'backstage'
      server: 'https://kubernetes.default.svc'
    - namespace: 'argocd'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: 'apiextensions.crossplane.io'      
      kind: '*'
    - group: 'pkg.crossplane.io'
      kind: '*'
    - group: 'apiextensions.k8s.io'
      kind: 'CustomResourceDefinition'