apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: bernardo-crossplane-s3-2526
  annotations:
    crossplane.io/external-name: bernardo-crossplane-s3-2526
spec:
  forProvider:
    region: us-east-1
  providerConfigRef:
    name: default
