apiVersion: v1          
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd     
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:platform-team, applications, *, */*, allow
    p, role:developer, applications, get, */*, allow
    p, role:developer, applications, sync, dev/*, allow

    g, platform-engineer, role:platform-team
    g, developer, role:developer