kind: ConfigMap
metadata:
  name: argocd-cm
data:
  # custom health checks
  # resource exclusions
  resource.exclusions: |
    - apiGroups:
      - "*"
      kinds:
      - ProviderConfigUsage
  # repository settings
  # SSO configuration
  # OIDC settings
  application.resourceTrackingMethod: annotation